### ISSUE TITLE
Longclick (Tap and hold) on transaction in closed account leads to crash

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#1063]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
       at org.totschnig.myexpenses.activity.BaseMyExpenses$startMyActionMode$1.onPrepareActionMode(BaseMyExpenses.kt:225)
       at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onPrepareActionMode(AppCompatDelegateImpl.java:3017)
       at androidx.appcompat.view.StandaloneActionMode.invalidate(StandaloneActionMode.java:100)
       at androidx.appcompat.app.AppCompatDelegateImpl.startSupportActionModeFromWindow(AppCompatDelegateImpl.java:1410)
       at androidx.appcompat.app.AppCompatDelegateImpl.startSupportActionMode(AppCompatDelegateImpl.java:1292)
       at androidx.appcompat.app.AppCompatActivity.startSupportActionMode(AppCompatActivity.java:367)
       at org.totschnig.myexpenses.activity.BaseMyExpenses.startMyActionMode(BaseMyExpenses.java:200)
       at org.totschnig.myexpenses.activity.BaseMyExpenses.access$startMyActionMode(BaseMyExpenses.java:113)
       at org.totschnig.myexpenses.activity.BaseMyExpenses$Page$1.invokeSuspend(BaseMyExpenses.kt:655)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by mtotschnig** [comment]
Regression in 3.4.7
