### ISSUE TITLE
Warn user about Android System backup not available with encrypted database

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#1120]
Followup to #291 : When user has opted into Encryption of database, we use a non-exportable key from Android Keystore, so the Android backup system will create a backup that can not be restored. this currently leads to app crashing on startup.

- Inform user about this limitation.
- Configure a backup agent that does not allow backup when database is encrypted.

**Comment by mtotschnig** [comment]
`Fatal Exception: com.google.crypto.tink.shaded.protobuf.b0: Protocol message contained an invalid tag (zero).
       at com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:125)
       at com.google.crypto.tink.shaded.protobuf.ArrayDecoders.decodeUnknownField(ArrayDecoders.java:1036)
       at com.google.crypto.tink.shaded.protobuf.MessageSchema.parseProto3Message(MessageSchema.java:5426)
       at com.google.crypto.tink.shaded.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5442)
       at com.google.crypto.tink.shaded.protobuf.ArrayDecoders.decodeMessageField(ArrayDecoders.java:246)
       at com.google.crypto.tink.shaded.protobuf.ArrayDecoders.decodeMessageList(ArrayDecoders.java:704)
       at com.google.crypto.tink.shaded.protobuf.MessageSchema.parseProto3Message(MessageSchema.java:5373)
       at com.google.crypto.tink.shaded.protobuf.MessageSchema.mergeFrom(MessageSchema.java:5442)
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1567)
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1680)
       at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:958)
       at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
       at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:61)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:332)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:288)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:239)
       at androidx.security.crypto.EncryptedFile$Builder.build(EncryptedFile.java:229)
       at org.totschnig.sqlcrypt.PassphraseRepository.getPassphrase(PassphraseRepository.java:36)
       at org.totschnig.sqlcrypt.SQLiteOpenHelperFactory.passPhrase(SQLiteOpenHelperFactory.kt:14)
       at org.totschnig.sqlcrypt.SQLiteOpenHelperFactory.provideEncryptedDatabase(SQLiteOpenHelperFactory.kt:16)
       at org.totschnig.sqlcrypt.SQLiteOpenHelperFactory.provideEncryptedDatabase(SQLiteOpenHelperFactory.kt:11)
       at org.totschnig.myexpenses.di.DataModule.provideSQLiteOpenHelper(DataModule.java:89)
       at org.totschnig.myexpenses.di.DataModule_ProvideSQLiteOpenHelperFactory.provideSQLiteOpenHelper(DataModule_ProvideSQLiteOpenHelperFactory.java:58)
       at org.totschnig.myexpenses.di.DataModule_ProvideSQLiteOpenHelperFactory.get(DataModule_ProvideSQLiteOpenHelperFactory.java:46)
       at org.totschnig.myexpenses.di.DataModule_ProvideSQLiteOpenHelperFactory.get(DataModule_ProvideSQLiteOpenHelperFactory.java:15)
       at org.totschnig.myexpenses.provider.BaseTransactionProvider.requireHelper(BaseTransactionProvider.kt:591)
       at org.totschnig.myexpenses.provider.BaseTransactionProvider.getHelper(BaseTransactionProvider.kt:62)
       at org.totschnig.myexpenses.provider.TransactionProvider.query(TransactionProvider.java:294)
       at android.content.ContentProvider.query(ContentProvider.java:1455)
       at android.content.ContentProvider.query(ContentProvider.java:1551)
       at android.content.ContentProvider$Transport.query(ContentProvider.java:285)
       at android.content.ContentResolver.query(ContentResolver.java:1219)
       at android.content.ContentResolver.query(ContentResolver.java:1151)
       at android.content.ContentResolver.query(ContentResolver.java:1107)
       at org.totschnig.myexpenses.model.Transaction.count(Transaction.java:1054)
       at org.totschnig.myexpenses.model.Template.updateNewPlanEnabled(Template.java:673)
       at org.totschnig.myexpenses.util.licence.LicenceHandler$update$1.invokeSuspend(LicenceHandler.kt:112)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`
