### ISSUE TITLE
Transaction list crashes when called from click on spent amount in budget if filter criteria are defined

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#1188]
```
Fatal Exception: android.database.sqlite.SQLiteException: no such column: transactions_extended.parent_id (code 1 SQLITE_ERROR): , while compiling: WITH Tree AS (
SELECT
    '' AS path,
    icon,
    _id
FROM categories main
WHERE _id = 46
UNION ALL
SELECT
    Tree.path || CASE WHEN Tree.path = '' THEN '' ELSE ' > ' END || subtree.label,
    subtree.icon,
    subtree._id
FROM categories subtree
JOIN Tree ON Tree._id = subtree.parent_id
), data AS ( SELECT transactions.*, Tree.path, Tree.icon, payee.name,paymentmethods.label AS method_label, planinstance_transaction.template_id, group_concat(tags.label,'') AS tag_list FROM transactions LEFT JOIN payee ON payee_id = payee._id LEFT JOIN paymentmethods ON method_id = paymentmethods._id LEFT JOIN Tree ON cat_id = TREE._id LEFT JOIN planinstance_transaction ON transactions._id = planinstance_transaction.transaction_id LEFT JOIN transactions_tags ON transactions_tags.transaction_id = transactions._id LEFT JOIN tags ON tag_id= tags._id WHERE status != 2  GROUP BY transactions._id) SELECT sum(amount) FROM data WHERE (cr_status != 'VOID' AND account_id = ? AND CAST(strftime('%Y',date,'unixepoch','localtime','-0 day') AS integer) = 2023 AND CAST(strftime('%m',date,'unixepoch','localtime','-0 day') AS integer) - 1 = 4 AND (cat_id IN (WITH Tree AS (
SELECT
    label,
    uuid,
    main.label AS path,
    color,
    icon,
    _id,
    parent_id,
    usages,
    last_used,
    1 AS level,
    1 AS matches
FROM categories main
WHERE  _id IN (?)
UNION ALL
SELECT
    subtree.label,
    subtree.uuid,
    Tree.path || ' > ' || subtree.label,
    subtree.color,
    subtree.icon,
    subtree._id,
    subtree.parent_id,
    subtree.usages,
    subtree.last_used,
    level + 1,
    1 AS matches
FROM categories subtree
JOIN Tree ON Tree._id = subtree.parent_id
ORDER BY level DESC
)SELECT _id FROM Tree ) OR  exists(select 1 from transactions parents WHERE _id = transactions_extended.parent_id AND (cat_id IN (WITH Tree AS (
SELECT
    label,
    uuid,
    main.label AS path,
    color,
    icon,
    _id,
    parent_id,
    usages,
    last_used,<truncated: 473 chars>
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
       at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1443)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1418)
       at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.kt:156)
       at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.kt:139)
       at org.totschnig.myexpenses.provider.BaseTransactionProvider$measureAndLogQuery$3.invoke(BaseTransactionProvider.kt:844)
       at org.totschnig.myexpenses.provider.BaseTransactionProvider$measureAndLogQuery$3.invoke(BaseTransactionProvider.kt:844)
       at org.totschnig.myexpenses.provider.BaseTransactionProvider$measureAndLogQuery$3.invoke(BaseTransactionProvider.kt:844)
       at org.totschnig.myexpenses.provider.BaseTransactionProvider.measure(BaseTransactionProvider.kt:850)
       at org.totschnig.myexpenses.provider.BaseTransactionProvider.measureAndLogQuery(BaseTransactionProvider.kt:844)
       at org.totschnig.myexpenses.provider.TransactionProvider.query(TransactionProvider.java:298)
       at android.content.ContentProvider.query(ContentProvider.java:1214)
       at android.content.ContentProvider.query(ContentProvider.java:1307)
       at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
       at android.content.ContentResolver.query(ContentResolver.java:946)
       at android.content.ContentResolver.query(ContentResolver.java:881)
       at android.content.ContentResolver.query(ContentResolver.java:837)
       at app.cash.copper.ContentResolverQuery.run(Query.kt:50)
       at app.cash.copper.flow.FlowContentResolver$mapToOne$$inlined$transform$1$1$lambda$1.invokeSuspend(FlowContentResolver.kt:151)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
``

**Comment by mtotschnig** [comment]
Similar crash when transaction list is opened from the Distribution screen for the Grand Total account is also fixed in version 3.5.6.
