### ISSUE TITLE
SQLiteException and crash

### ISSUE THREAD

**Issue by StefanieZwj** [mtotschnig/MyExpenses#1352]
ACRA caught a SQLiteException for org.totschnig.myexpenses.debug
                                                                                                    android.database.sqlite.SQLiteException: integer overflow (code 1 SQLITE_ERROR)
                                                                                                    	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
                                                                                                    	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1024)
                                                                                                    	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
                                                                                                    	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                                                                    	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:145)
                                                                                                    	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                                                                                                    	at org.totschnig.myexpenses.provider.BaseTransactionProvider.measure(BaseTransactionProvider.kt:982)
                                                                                                    	at org.totschnig.myexpenses.provider.BaseTransactionProvider.measureAndLogQuery(BaseTransactionProvider.kt:890)
                                                                                                    	at org.totschnig.myexpenses.provider.TransactionProvider.query(TransactionProvider.java:870)
                                                                                                    	at android.content.ContentProvider.query(ContentProvider.java:1455)
                                                                                                    	at android.content.ContentProvider.query(ContentProvider.java:1551)
                                                                                                    	at android.content.ContentProvider$Transport.query(ContentProvider.java:285)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1219)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1151)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1107)
                                                                                                    	at app.cash.copper.ContentResolverQuery.run(Query.kt:50)
                                                                                                    	at app.cash.copper.flow.FlowContentResolver$mapToOne$$inlined$transform$1$1$lambda$1.invokeSuspend(FlowContentResolver.kt:151)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b134ef9, Dispatchers.Main.immediate]
2023-12-22 13:37:39.758   231-231   SELinux                 servicemanager                       E  avc:  denied  { find } for pid=7225 uid=10162 name=meminfo scontext=u:r:untrusted_app:s0:c162,c256,c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
---------------------------- PROCESS ENDED (4214) for package org.totschnig.myexpenses.debug ----------------------------
2023-12-22 13:37:40.168   428-428   ClientCache             surfaceflinger                       E  failed to get buffer, invalid process token
2023-12-22 13:37:40.169   428-428   BpTransact...edListener surfaceflinger                       E  Failed to transact (-32)

**Comment by mtotschnig** [comment]
@StefanieZwj Thank you for the report. Could you describe if the crash is reproducible and if yes describe the scenario that triggers it? If you were able to send the email generated by ACRA, it would give me some more hints about the context of the crash.
