### ISSUE TITLE
WindowLeaked in Activity  MyExpenses

### ISSUE THREAD

**Issue by WhiteSeele** [mtotschnig/MyExpenses#1496]
05-04 17:00:47.162 22681 22681 E WindowManager:
05-04 17:00:47.162 22681 22681 E WindowManager: android.view.WindowLeaked: Activity org.totschnig.myexpenses.activity.MyExpenses has leaked window android.widget.PopupWindow$PopupDecorView{c4536fe V.E...... ......ID 0,0-649,1680} that was originally added here
05-04 17:00:47.162 22681 22681 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1258)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1110)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at androidx.appcompat.widget.AppCompatPopupWindow.showAsDropDown(AppCompatPopupWindow.java)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at androidx.core.widget.PopupWindowCompat$Api19Impl.showAsDropDown(PopupWindowCompat.java)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at androidx.core.widget.PopupWindowCompat.showAsDropDown(PopupWindowCompat.java)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at androidx.appcompat.widget.ListPopupWindow.show(ListPopupWindow.java)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at androidx.appcompat.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at androidx.appcompat.view.menu.StandardMenuPopup.show(StandardMenuPopup.java)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at androidx.appcompat.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at androidx.appcompat.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at androidx.appcompat.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:739)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at android.os.Looper.loop(Looper.java:148)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-04 17:00:47.162 22681 22681 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mtotschnig** [comment]
Thank you for the report. Is the crash reproducible? Can you describe the scenario that has triggered it?
