### ISSUE TITLE
Fdroid build crashes after install - "Invalid key: app_name"

### ISSUE THREAD

**Issue by astroanax** [mtotschnig/MyExpenses#1556]
Happens when trying to open the app for the first time after install, on android 14. Google play build works fine though. Version 3.8.7.1
```
09-04 01:08:07.487 I/hnig.myexpenses(14525): Using CollectorTypeCC GC.
09-04 01:08:07.491 E/hnig.myexpenses(14525): Not starting debugger since process cannot load the jdwp agent.
09-04 01:08:07.509 D/nativeloader(14525): Load libframework-connectivity-tiramisu-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity-t.jar: ok
09-04 01:08:07.526 D/CompatibilityChangeReporter(14525): Compat change id reported: 171979766; UID 10512; state: ENABLED
09-04 01:08:07.526 D/CompatibilityChangeReporter(14525): Compat change id reported: 242716250; UID 10512; state: ENABLED
09-04 01:08:07.535 D/nativeloader(14525): Configuring clns-4 for other apk /data/app/~~CVtK4n6TrWt3885Kx31DOA==/org.totschnig.myexpenses-RLFiLi1LXX9goSCSH-hiMA==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~CVtK4n6TrWt3885Kx31DOA==/org.totschnig.myexpenses-RLFiLi1LXX9goSCSH-hiMA==/lib/arm64:/data/app/~~CVtK4n6TrWt3885Kx31DOA==/org.totschnig.myexpenses-RLFiLi1LXX9goSCSH-hiMA==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/org.totschnig.myexpenses
09-04 01:08:07.543 V/GraphicsEnvironment(14525): Currently set values for:
09-04 01:08:07.543 V/GraphicsEnvironment(14525):   angle_gl_driver_selection_pkgs=[com.android.angle, com.linecorp.b612.android, com.campmobile.snow, com.google.android.apps.tachyon]
09-04 01:08:07.543 V/GraphicsEnvironment(14525):   angle_gl_driver_selection_values=[angle, native, native, native]
09-04 01:08:07.543 V/GraphicsEnvironment(14525): org.totschnig.myexpenses is not listed in per-application setting
09-04 01:08:07.543 V/GraphicsEnvironment(14525): Neither updatable production driver nor prerelease driver is supported.
09-04 01:08:07.545 I/LoadedApk(14525): No resource references to update in package org.totschnig.myexpenses.onedrive
09-04 01:08:07.545 I/LoadedApk(14525): No resource references to update in package org.totschnig.myexpenses.fints
09-04 01:08:07.545 I/LoadedApk(14525): No resource references to update in package org.totschnig.myexpenses.sqlcrypt
09-04 01:08:07.545 I/LoadedApk(14525): No resource references to update in package org.totschnig.myexpenses.webdav
09-04 01:08:07.545 I/LoadedApk(14525): No resource references to update in package org.totschnig.myexpenses.ocr
09-04 01:08:07.557 W/hnig.myexpenses(14525): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, denied)
09-04 01:08:07.557 W/hnig.myexpenses(14525): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, denied)
09-04 01:08:07.558 W/hnig.myexpenses(14525): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, denied)
09-04 01:08:07.578 D/AndroidRuntime(14525): Shutting down VM
09-04 01:08:07.579 E/AndroidRuntime(14525): FATAL EXCEPTION: main
09-04 01:08:07.579 E/AndroidRuntime(14525): Process: org.totschnig.myexpenses, PID: 14525
09-04 01:08:07.579 E/AndroidRuntime(14525): java.lang.RuntimeException: Unable to instantiate application org.totschnig.myexpenses.MyApplication package org.totschnig.myexpenses: java.lang.IllegalArgumentException: Invalid key: app_name
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1474)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7361)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.os.Looper.loopOnce(Looper.java:232)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.os.Looper.loop(Looper.java:317)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.app.ActivityThread.main(ActivityThread.java:8594)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at java.lang.reflect.Method.invoke(Native Method)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
09-04 01:08:07.579 E/AndroidRuntime(14525): Caused by: java.lang.IllegalArgumentException: Invalid key: app_name
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at s4.a.c(Phrase.java:42)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at org.totschnig.myexpenses.util.y.j(Utils.java:23)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at org.totschnig.myexpenses.util.crashreporting.AcraCrashHandler$onAttachBaseContext$1$1.invoke(AcraCrashHandler.kt:32)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at org.totschnig.myexpenses.util.crashreporting.AcraCrashHandler$onAttachBaseContext$1.invoke(AcraCrashHandler.kt:88)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at org.totschnig.myexpenses.util.crashreporting.AcraCrashHandler.e(AcraCrashHandler.kt:18)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at org.totschnig.myexpenses.MyApplication.attachBaseContext(MyApplication.kt:95)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.app.Application.attach(Application.java:346)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1355)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
09-04 01:08:07.579 E/AndroidRuntime(14525): 	... 11 more
```

**Comment by mtotschnig** [comment]
@astroanax Thanks a lot for the report. I can reproduce this if app is started with Urdu locale. This kind of problem should normally have been verified by a unit test, but unfortunately this test was not run for Urdu. Will be fixed in next version. As a workaround, you can configure the app to run with a different locale via system settings -> Apps -> MyExpenses -> Language.

**Comment by mtotschnig** [comment]
Updated via Weblate and added Urdu to languages.
