### ISSUE TITLE
Fix Boot_completed on Oreo

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#417]
On Oreo, scheduling auto backup from boot_completed does not work and leads to following crash
```
java.lang.RuntimeException: Unable to start receiver org.totschnig.myexpenses.service.GenericAlarmReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=org.totschnig.myexpenses.ACTION_SCHEDULE_AUTO_BACKUP cmp=org.totschnig.myexpenses/.service.AutoBackupService }: app is in background uid UidRecord{7655db1 u0a189 RCVR idle procs:1 seq(0,0,0)}
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
at android.app.ActivityThread.-wrap17(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=org.totschnig.myexpenses.ACTION_SCHEDULE_AUTO_BACKUP cmp=org.totschnig.myexpenses/.service.AutoBackupService }: app is in background uid UidRecord{7655db1 u0a189 RCVR idle procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
at android.app.ContextImpl.startService(ContextImpl.java:1461)
at android.content.ContextWrapper.startService(ContextWrapper.java:644)
at android.content.ContextWrapper.startService(ContextWrapper.java:644)
at com.c.a.a.a.a(WakefulIntentService.java:48)
at org.totschnig.myexpenses.service.GenericAlarmReceiver.a(GenericAlarmReceiver.java:54)
at org.totschnig.myexpenses.service.GenericAlarmReceiver.onReceive(GenericAlarmReceiver.java:40)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
... 8 more
java.lang.IllegalStateException: Not allowed to start service Intent { act=org.totschnig.myexpenses.ACTION_SCHEDULE_AUTO_BACKUP cmp=org.totschnig.myexpenses/.service.AutoBackupService }: app is in background uid UidRecord{7655db1 u0a189 RCVR idle procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
at android.app.ContextImpl.startService(ContextImpl.java:1461)
at android.content.ContextWrapper.startService(ContextWrapper.java:644)
at android.content.ContextWrapper.startService(ContextWrapper.java:644)
at com.c.a.a.a.a(WakefulIntentService.java:48)
at org.totschnig.myexpenses.service.GenericAlarmReceiver.a(GenericAlarmReceiver.java:54)
at org.totschnig.myexpenses.service.GenericAlarmReceiver.onReceive(GenericAlarmReceiver.java:40)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
at android.app.ActivityThread.-wrap17(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Possible solutions outlined in https://commonsware.com/blog/2017/06/12/action_boot_completed-intentservice-android-8p0.html

**Comment by mtotschnig** [comment]
fixed with 8e8a9dd04c3cf7b950ad3094e89b63389ff6b971
