### ISSUE TITLE
Crash when moving accounts down with custom sort order

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#420]
```
java.lang.IllegalArgumentException: Unknown URL content://org.totschnig.myexpenses/accounts/swapSortKey/null/1
at org.totschnig.myexpenses.provider.TransactionProvider.a(TransactionProvider.java:828)
at org.totschnig.myexpenses.provider.TransactionProvider.update(TransactionProvider.java:1416)
at android.content.ContentProvider$Transport.update(ContentProvider.java:360)
at android.content.ContentResolver.update(ContentResolver.java:1413)
at org.totschnig.myexpenses.f.d.doInBackground(GenericTask.java:263)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)
```

**Comment by mtotschnig** [comment]
fixed with eddbe624435d2980a6d4f785df20924f73021558
