### ISSUE TITLE
window leak in ExpenseEdit

### ISSUE THREAD

**Issue by anlalalu** [mtotschnig/MyExpenses#605]
###### Reproduction Steps

1. go to edit transaction interface
2. long click 'more options'
3. click 'save' quickly

###### Stack Trace

E/WindowManager: android.view.WindowLeaked: Activity org.totschnig.myexpenses.activity.ExpenseEdit has leaked window android.widget.LinearLayout{7fbe9dd V.E...... ......ID 0,0-260,96} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                    at android.support.v7.widget.TooltipPopup.show(TooltipPopup.java:86)
                                                    at android.support.v7.widget.TooltipCompatHandler.show(TooltipCompatHandler.java:174)
                                                    at android.support.v7.widget.TooltipCompatHandler.onLongClick(TooltipCompatHandler.java:123)
                                                    at android.view.View.performLongClickInternal(View.java:5714)
                                                    at android.view.View.performLongClick(View.java:5672)
                                                    at android.view.View.performLongClick(View.java:5690)
                                                    at android.view.View$CheckForLongPress.run(View.java:22398)
                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:154)
                                                    at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

###### Debug info
App Version = r377

Android Version = 7.1.0

**Comment by mtotschnig** [comment]
Thank you for the report. Could you verify, if the same can be reproduced with latest version 393 ?
