### ISSUE TITLE
RuntimeException in Activity MyExpenses

### ISSUE THREAD

**Issue by seg-ha** [mtotschnig/MyExpenses#643]
E/ActivityThread(10945): Performing pause of activity that is not resumed: {org.totschnig.myexpenses/org.totschnig.myexpenses.activity.MyExpenses}
E/ActivityThread(10945): java.lang.RuntimeException: Performing pause of activity that is not resumed: {org.totschnig.myexpenses/org.totschnig.myexpenses.activity.MyExpenses}
E/ActivityThread(10945): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3015)
E/ActivityThread(10945): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3003)
E/ActivityThread(10945): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2981)
E/ActivityThread(10945): 	at android.app.ActivityThread.access$1000(ActivityThread.java:135)
E/ActivityThread(10945): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
E/ActivityThread(10945): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread(10945): 	at android.os.Looper.loop(Looper.java:136)
E/ActivityThread(10945): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/ActivityThread(10945): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/ActivityThread(10945): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/ActivityThread(10945): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/ActivityThread(10945): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/ActivityThread(10945): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by mtotschnig** [comment]
Thank you for the report. Is the crash reproducible? Can you describe the scenario that has triggered it?
