### ISSUE TITLE
Cannot load accounts from WebDAV synchronization backend with passphrase

### ISSUE THREAD

**Issue by tfoarulz** [mtotschnig/MyExpenses#677]
MyExpenses version: 3.1.3.1 (version 422) from F-Droid
License type: Extended Key
NextCloud version: 19.0.2

I have created a WebDAV synchronization backend with passphrase and the sync seems working. However, when I try to click on the synchronization backend to list the available accounts, each account shows "java.security.GeneralSecurityException: Invalid Magic Number". This only happens to encrypted backend with passphrase. I tried with an unencrypted backend, the accounts can be listed successfully and I can choose any accounts to be synced with.

The SyncAdapter-latest.log shows multiple paragraphs of text as below:

----- START LOG -----
 2020-09-07 13:43:29,587 ERROR [DefaultDispatcher-worker-1] java.io.IOException: java.security.GeneralSecurityException: Invalid Magic Number
	at org.totschnig.myexpenses.sync.o0.T(AbstractSyncBackendProvider.java:2)
	at org.totschnig.myexpenses.sync.o0.u(AbstractSyncBackendProvider.java:1)
	at org.totschnig.myexpenses.sync.y0.i0(WebDavBackendProvider.java:1)
	at org.totschnig.myexpenses.sync.y0.n0(Unknown Source:0)
	at org.totschnig.myexpenses.sync.f0.a(Unknown Source:4)
	at h.c.a.m.k.a(ObjMap.java:1)
	at h.c.a.l.d.next(LsaIterator.java:2)
	at h.c.a.i.e(Stream.java:3)
	at org.totschnig.myexpenses.k.c0$a$a.b(SyncBackendViewModel.kt:1)
	at org.totschnig.myexpenses.k.c0$a$a.a(SyncBackendViewModel.kt:1)
	at h.c.a.c.e(Exceptional.java:4)
	at org.totschnig.myexpenses.k.c0$a.v(SyncBackendViewModel.kt:4)
	at org.totschnig.myexpenses.k.c0$a.o(Unknown Source:10)
	at androidx.lifecycle.b$b.v(CoroutineLiveData.kt:5)
	at n.u.j.a.a.n(ContinuationImpl.kt:3)
	at kotlinx.coroutines.t0.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.s2.b.B(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.s2.b$a.c(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.s2.b$a.m(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.s2.b$a.run(CoroutineScheduler.kt:1)
Caused by: java.security.GeneralSecurityException: Invalid Magic Number
	at org.totschnig.myexpenses.j.q0.a.a(EncryptionHelper.java:8)
	at org.totschnig.myexpenses.sync.o0.T(AbstractSyncBackendProvider.java:1)
	... 19 more
----- END LOG -----

**Comment by mtotschnig** [comment]
This most probably is caused by the web server not handling chunked-transfer encoding correctly. See here on a related problem report with suggested solutions: https://trac.cyberduck.io/wiki/help/en/howto/mount/issues/fastcgi#Recommendedconfiguration

**Comment by mtotschnig** [comment]
I am not aware of a reliable recipe for making this work with NextCloud: The related issue is still open: https://github.com/nextcloud/server/issues/7995.
