### ISSUE TITLE
crash and exit on AVD during use WebDAV

### ISSUE THREAD

**Issue by jyjsunny** [mtotschnig/MyExpenses#984]
###### Reproduction Steps
Since I can't reproduce the bug on AVD, I don't know what triggered it.

###### video(on AVD)

https://user-images.githubusercontent.com/92309998/169187963-90727d97-db28-4aa8-b3a9-36388f02a2c8.mov

###### Stack Trace
: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
: 	at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:484)
: 	at android.app.assist.AssistStructure.<init>(AssistStructure.java:1908)
: 	at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3035)
: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807)
: 	at android.os.Handler.dispatchMessage(Handler.java:105)
: 	at android.os.Looper.loop(Looper.java:164)
: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
: 	at java.lang.reflect.Method.invoke(Native Method)
: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by mtotschnig** [comment]
Thank you for the report? Did you use a version of the app distributed on an app-store, or build it yourself?

**Comment by jyjsunny** [comment]
Thank you for your reply, and I am using the version of the app released in the app store, the version number is 515.

**Comment by mtotschnig** [comment]
@jyjsunny Could you be more precise and explain from which app store you downloaded the app? Send a feedback request from the app's settings or add a screenshot of the Licence & Credits screen.

**Comment by jyjsunny** [comment]
> Could you be more precise and explain from which app store you downloaded the app? Send a feedback request from the app's settings or add a screenshot of the Licence & Credits screen.

@mtotschnig Thank you for your reply, and I downloaded it from Google Play, and the apk version is 515.(org.totschnig.myexpenses_515.apk)

**Comment by mtotschnig** [comment]
Do I understand you correctly, that you sideload an APK downloaded on one device to another device? This is not supported and will lead to crashes. The reason is that Play Store creates APKs on demand for specific devices only including the resources needed for that device. If you use that APK on a different device, resources necessary there will be missing from the APK and lead to crash.
If you need My Expenses on a device without Play services, please use the version from F-Droid.

**Comment by jyjsunny** [comment]
> Do I understand you correctly, that you sideload an APK downloaded on one device to another device? This is not supported and will lead to crashes. The reason is that Play Store creates APKs on demand for specific devices only including the resources needed for that device. If you use that APK on a different device, resources necessary there will be missing from the APK and lead to crash. If you need My Expenses on a device without Play services, please use the version from F-Droid.

Thank you for your reply. 

Sorry, I misremembered before, the version I tested was downloaded on F-Droid with version number 3.3.7. (The version number where the bug was found was 3.3.7)
